name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: format
        run: make format
      - name: test
        run: make test
      - name: test
        env:
          DATABRICKS_KEY: ${{ secrets.DATABRICKS_TOKEN }}
          SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
          HTTP_PATH: ${{ secrets.HTTP_PATH }}
        run: make test
